language: python
sudo: false


# We don't care about Travis' python versions, we install conda anyway

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  #- "3.4"
  - "3.5" # TODO

env:
  global:
    - AWS_DEFAULT_REGION=eu-west-1

before_install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels 'http://conda.anaconda.org/babbel'
  - conda info -a

install:
  # Install dependencies
  - conda env create -n testenv_$TRAVIS_PYTHON_VERSION python=$TRAVIS_PYTHON_VERSION
  - source activate testenv_$TRAVIS_PYTHON_VERSION
  - conda install boto3 pytest pytest-mock pytest-pythonpath
script:
  - py.test -rsxX -q

notifications:
  email: true