language: python
sudo: false

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.4"
  - "3.5"


before_install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels 'http://conda.anaconda.org/babbel'
  - conda info -a

install:
  # Install dependencies
  - conda env create -n testenv_$python -f $TRAVIS_BUILD_DIR/conda-test-environment.yml
  - source activate testenv_$python

script:
  - py.test -vv -r sxX

notifications:
  email: true