# conda env create -f conda-dev-environment.yml
# to change the name:  conda env create -n piping-test -f conda-dev-environment.yml
name: testpyscala-dev
dependencies:
- betamax=0.5.1=py35_0
- boto3=1.2.3=py35_0
- botocore=1.3.27=py35_0
- cffi=1.5.2=py35_0
- coverage=4.0.3=py35_0
- cryptography=1.0.2=py35_0
- docutils=0.12=py35_0
- ecdsa=0.13=py35_0
- gcloud=0.11.0=py35_0
- googleapis-common-protos=1.1.0=py35_0
- httplib2=0.9.2=py35_0
- idna=2.0=py35_0
- jmespath=0.9.0=py35_0
# not available on osx, but doesn't matter
# - libffi=3.0.13=0
- mkl=11.3.1=0
- numexpr=2.5=np110py35_0
# not available on osx, another one will be installed
# - numpy=1.10.4=py35_1
- oauth2client=2.0.1=py35_0
- openssl=1.0.2g=0
- pandas=0.18.0=np110py35_0
- paramiko=1.15.3=py35_0
- pip=8.1.0=py35_0
- protobuf=3.0.0b2.post2=py35_0
- py=1.4.31=py35_0
- pyasn1=0.1.9=py35_0
- pyasn1-modules=0.0.8=py35_0
- pycparser=2.14=py35_0
- pycrypto=2.6.1=py35_0
- pymysql=0.6.7=py35_0
- pyopenssl=0.15.1=py35_1
- pytest=2.8.5=py35_0
- pytest-cov=2.2.1=py35_0
- pytest-mock=0.11.0=py35_0
- pytest-pythonpath=0.7=py35_0
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- pytz=2015.7=py35_0
- pyyaml=3.11=py35_1
- readline=6.2=2
- requests=2.9.1=py35_0
- rsa=3.3=py35_0
- setuptools=20.2.2=py35_0
- six=1.10.0=py35_0
- sqlalchemy=1.0.12=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- toolz=0.7.4=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - hypothesis>=3.1.0